AWSTemplateFormatVersion: '2010-09-09'
Description: Kaspa Solo Miner – Single EC2 Instance with Docker + GPU

Parameters:
  InstanceType:
    Type: String
    Default: g5.xlarge
    Description: GPU-enabled EC2 instance type
  KaspaWallet:
    Type: String 
    Default: qqypu226z2et65wnwcz5dmt74azka0k6g28vqm4tuxdz694udqzp2stt55eq3
    Description: Your Kaspa wallet address
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-088f6cb7a04c21d34
    Description: Subnet within your VPC

Resources:
  KaspaMinerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and Stratum traffic
      VpcId: vpc-037436d429c6e7de0
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 16112
          ToPort: 16112
          CidrIp: 0.0.0.0/0

  KaspaMinerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: kaspa
      #ImageId: ami-03aa99ddf5498ceb9  # DZ found by searching AMI catelog
      ImageId: ami-0d561be146bd8c20e
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref KaspaMinerSecurityGroup
      Tags:
        - Key: Name
          Value: KaspaSoloMiner
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo -i << 'EOF'
          exec > /var/log/userdata.log 2>&1
          set -x
          apt update && apt upgrade -y
          apt install -y docker.io unzip curl git screen
          systemctl start docker
          systemctl enable docker

          # Install NVIDIA drivers
          apt install -y nvidia-driver-535

          curl -L "https://github.com/docker/compose/releases/download/v2.24.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          
          # Clone Kaspa node + Stratum setup
          cd ~
          git clone --branch Usage --single-branch https://github.com/danz50of/Kaspa-Full-Node-Mining-Quick-Start.git
          cd Kaspa-Full-Node-Mining-Quick-Start

          ./tldr.sh

          # Install lolMiner
          cd ~
          wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.82/lolMiner_v1.82_Lin64.tar.gz
          tar -xvzf lolMiner_v1.82_Lin64.tar.gz
          cd lolMiner_v1.82
          chmod +x lolMiner    

          # Start mining
          screen -dmS kaspa-miner ./lolMiner --algo KASPA \
            --pool 127.0.0.1:16112 \
            --user ${KaspaWallet}

          EOF

Outputs:
  InstancePublicIP:
    Description: Public IP of the Kaspa miner
    Value: !GetAtt KaspaMinerInstance.PublicIp